'use strict';
const WORDS = [
  {
    id: 1,
    day: 1,
    english: 'able',
    spanish: 'capaz',
    example: 'She is able to walk for hours.',
  },
  {
    id: 2,
    day: 2,
    english: 'absolutely',
    spanish: 'absolutamente',
    example: 'It is absolutely necessary to eat healthy food.',
  },
  {
    id: 3,
    day: 3,
    english: 'act',
    spanish: 'actuar',
    example: 'I should act as you advise.',
  },
  {
    id: 4,
    day: 4,
    english: 'actually',
    spanish: 'en realidad',
    example: "I'm not sure if this actually happened.",
  },
  {
    id: 5,
    day: 5,
    english: 'afraid',
    spanish: 'temerozo/temeroza',
    example: "She's afraid of spiders.",
  },
  {
    id: 6,
    day: 6,
    english: 'again',
    spanish: 'otra vez',
    example: 'You should try it again.',
  },
  {
    id: 7,
    day: 7,
    english: 'ago',
    spanish: 'hace',
    example: 'I went to New York a month ago.',
  },
  {
    id: 8,
    day: 8,
    english: 'agree',
    spanish: 'estar de acuerdo',
    example: "The workers agree with the company's new policy.",
  },
  {
    id: 9,
    day: 9,
    english: 'ahead',
    spanish: 'adelante',
    example: 'Go ahead and take a seat.',
  },
  {
    id: 10,
    day: 10,
    english: 'air',
    spanish: 'aire',
    example: 'I like fresh air.',
  },
  {
    id: 11,
    day: 11,
    english: 'alive',
    spanish: 'vivo/viva',
    example: "I'm glad to be alive.",
  },
  {
    id: 12,
    day: 12,
    english: 'allow',
    spanish: 'permitir',
    example: "They don't allow pets.",
  },
  {
    id: 13,
    day: 13,
    english: 'almost',
    spanish: 'casi',
    example: 'It is almost dark.',
  },
  {
    id: 14,
    day: 14,
    english: 'alone',
    spanish: 'solo/sola',
    example: "I don't want to go alone.",
  },
  {
    id: 15,
    day: 15,
    english: 'already',
    spanish: 'ya',
    example: 'I have already visited this town.',
  },
  {
    id: 16,
    day: 16,
    english: 'alright',
    spanish: 'bien',
    example: "It's alright.",
  },
  {
    id: 17,
    day: 17,
    english: 'also',
    spanish: 'además',
    example: 'He also plays the piano.',
  },
  {
    id: 18,
    day: 18,
    english: 'always',
    spanish: 'siempre',
    example: 'They always eat vegetables.',
  },
  {
    id: 19,
    day: 19,
    english: 'amaze',
    spanish: 'asombrar',
    example: 'The singer amazed the audience.',
  },
  {
    id: 20,
    day: 20,
    english: 'animal',
    spanish: 'animal',
    example: "What's your favorite animal?",
  },
  {
    id: 21,
    day: 1,
    english: 'answer',
    spanish: 'respuesta',
    example: "The student doesn't know the answer.",
  },
  {
    id: 22,
    day: 2,
    english: 'answer',
    spanish: 'responder/contestar (verb)',
    example: 'Can you answer the phone?',
  },
  {
    id: 23,
    day: 3,
    english: 'anymore',
    spanish: 'nunca más',
    example: "I didn't see him anymore.",
  },
  {
    id: 24,
    day: 4,
    english: 'anyway',
    spanish: 'de todos modos',
    example: "I'll go anyway.",
  },
  {
    id: 25,
    day: 5,
    english: 'apartment',
    spanish: 'departamento',
    example: 'I have a big apartment.',
  },
  {
    id: 26,
    day: 6,
    english: 'apologize',
    spanish: 'pedir disculpas',
    example: 'I apologize for this trouble.',
  },
  {
    id: 27,
    day: 7,
    english: 'appreciate',
    spanish: 'apreciar',
    example: 'We appreciate your help.',
  },
  {
    id: 28,
    day: 8,
    english: 'arm',
    spanish: 'brazo',
    example: 'My arm hurts a bit.',
  },
  {
    id: 29,
    day: 9,
    english: 'art',
    spanish: 'arte',
    example: 'She enjoys abstract art.',
  },
  {
    id: 30,
    day: 10,
    english: 'ask',
    spanish: 'preguntar/pedir',
    example: 'I was going to ask you.',
  },
  {
    id: 31,
    day: 11,
    english: 'attention',
    spanish: 'atención',
    example: 'Please, pay attention.',
  },
  {
    id: 32,
    day: 12,
    english: 'away',
    spanish: 'lejos',
    example: 'She lives away from here.',
  },
  {
    id: 33,
    day: 13,
    english: 'awesome',
    spanish: 'asombroso/asombrosa',
    example: 'This song is awesome.',
  },
  {
    id: 34,
    day: 14,
    english: 'baby',
    spanish: 'bebé',
    example: 'The baby is sleeping.',
  },
  {
    id: 35,
    day: 15,
    english: 'back',
    spanish: 'atrás',
    example: 'There is no way back,',
  },
  {
    id: 36,
    day: 16,
    english: 'back',
    spanish: 'espalda (noun)',
    example: 'The injury was on his back.',
  },
  {
    id: 37,
    day: 17,
    english: 'bad',
    spanish: 'malo/mala',
    example: 'This is bad news.',
  },
  {
    id: 38,
    day: 18,
    english: 'bag',
    spanish: 'bolsa/mochila/bolso',
    example: 'Her bag is brown and black.',
  },
  {
    id: 39,
    day: 19,
    english: 'ball',
    spanish: 'pelota',
    example: 'The ball is under the bed.',
  },
  {
    id: 40,
    day: 20,
    english: 'band',
    spanish: 'banda',
    example: 'The band is going to perform at the theater.',
  },
  {
    id: 41,
    day: 1,
    english: 'bar',
    spanish: 'bar',
    example: 'The bar was really crowded.',
  },
  {
    id: 42,
    day: 2,
    english: 'bathroom',
    spanish: 'baño',
    example: 'The house has three bathrooms.',
  },
  {
    id: 43,
    day: 3,
    english: 'be',
    spanish: 'ser/estar',
    example: "Let's be friends.",
  },
  {
    id: 44,
    day: 4,
    english: 'bear',
    spanish: 'soportar',
    example: "I can't bear this heat.",
  },
  {
    id: 45,
    day: 5,
    english: 'beat',
    spanish: 'golpear',
    example: 'The waves beat against the cliff.',
  },
  {
    id: 46,
    day: 6,
    english: 'beautiful',
    spanish: 'bello/bella/hermoso/hermosa',
    example: 'The picture is beautiful.',
  },
  {
    id: 47,
    day: 7,
    english: 'become',
    spanish: 'convertirse',
    example: 'She wants to become a teacher.',
  },
  {
    id: 48,
    day: 8,
    english: 'bed',
    spanish: 'cama',
    example: 'My bed is comfortable.',
  },
  {
    id: 49,
    day: 9,
    english: 'beer',
    spanish: 'cerveza',
    example: 'Would you like some beer?',
  },
  {
    id: 50,
    day: 10,
    english: 'begin',
    spanish: 'comenzar',
    example: 'The school year is about to begin.',
  },
  {
    id: 51,
    day: 11,
    english: 'believe',
    spanish: 'creer',
    example: 'I believe in you.',
  },
  {
    id: 52,
    day: 12,
    english: 'bet',
    spanish: 'apostar',
    example: 'I bet they will win.',
  },
  {
    id: 53,
    day: 13,
    english: 'big',
    spanish: 'gran/grande',
    example: 'Elephants are big.',
  },
  {
    id: 54,
    day: 14,
    english: 'birthday',
    spanish: 'cumpleaños',
    example: 'Today is my birthday.',
  },
  {
    id: 55,
    day: 15,
    english: 'bite',
    spanish: 'morder',
    example: 'Be careful, that dog can bite you.',
  },
  {
    id: 56,
    day: 16,
    english: 'black',
    spanish: 'negro/negra',
    example: "I'm wearing a black coat.",
  },
  {
    id: 57,
    day: 17,
    english: 'blood',
    spanish: 'sangre',
    example: "What's your blood type?",
  },
  {
    id: 58,
    day: 18,
    english: 'blow',
    spanish: 'soplar',
    example: 'The wind is blowing very strongly.',
  },
  {
    id: 59,
    day: 19,
    english: 'blue',
    spanish: 'azul',
    example: 'Her blue dress is stunning.',
  },
  {
    id: 60,
    day: 20,
    english: 'boat',
    spanish: 'bote',
    example: 'There are many boats on the river.',
  },
  {
    id: 61,
    day: 1,
    english: 'body',
    spanish: 'cuerpo',
    example: 'How can we make our body healthy?',
  },
  {
    id: 62,
    day: 2,
    english: 'book',
    spanish: 'libro',
    example: 'The library has a huge amount of books.',
  },
  {
    id: 63,
    day: 3,
    english: 'boss',
    spanish: 'jefe/jefa',
    example: 'My boss is very kind.',
  },
  {
    id: 64,
    day: 4,
    english: 'box',
    spanish: 'caja',
    example: 'The toys are in the box.',
  },
  {
    id: 65,
    day: 5,
    english: 'boy',
    spanish: 'niño',
    example: 'The boy is doing his homework.',
  },
  {
    id: 66,
    day: 6,
    english: 'boyfriend',
    spanish: 'novio',
    example: 'Her boyfriend is tall.',
  },
  {
    id: 67,
    day: 7,
    english: 'brain',
    spanish: 'cerebro',
    example: 'We learnt about the structure of the brain today.',
  },
  {
    id: 68,
    day: 8,
    english: 'break',
    spanish: 'romper',
    example: "Let's break the rules.",
  },
  {
    id: 69,
    day: 9,
    english: 'bring',
    spanish: 'traer',
    example: 'You can bring your pet with you.',
  },
  {
    id: 70,
    day: 10,
    english: 'brother',
    spanish: 'hermano',
    example: 'My brother is a bad student.',
  },
  {
    id: 71,
    day: 11,
    english: 'buddy',
    spanish: 'amigo',
    example: 'I went to the show with a buddy of mine.',
  },
  {
    id: 72,
    day: 12,
    english: 'build',
    spanish: 'construir',
    example: 'They want to build a house in that place.',
  },
  {
    id: 73,
    day: 13,
    english: 'bunch',
    spanish: 'grupo',
    example: 'There is a bunch of people waiting for him.',
  },
  {
    id: 74,
    day: 13,
    english: 'burn',
    spanish: 'arder',
    example: 'Green wood does not burn well.',
  },
  {
    id: 75,
    day: 15,
    english: 'bus',
    spanish: 'autobús',
    example: 'We missed the bus.',
  },
  {
    id: 76,
    day: 16,
    english: 'business',
    spanish: 'negocio',
    example: "I'm going to start my own business.",
  },
  {
    id: 77,
    day: 17,
    english: 'busy',
    spanish: 'ocupado/ocupada',
    example: 'You have been really busy lately.',
  },
  {
    id: 78,
    day: 18,
    english: 'buy',
    spanish: 'comprar',
    example: 'I need to buy shoes.',
  },
  {
    id: 79,
    day: 19,
    english: 'cake',
    spanish: 'pastel/torta',
    example: 'I love chocolate cake.',
  },
  {
    id: 80,
    day: 20,
    english: 'call',
    spanish: 'llamar (verb)',
    example: 'Can you call him after 5 PM?',
  },
  {
    id: 81,
    day: 1,
    english: 'call',
    spanish: 'llamada',
    example: 'I took an urgent call.',
  },
  {
    id: 82,
    day: 2,
    english: 'can',
    spanish: 'poder',
    example: 'They can play the guitar.',
  },
  {
    id: 83,
    day: 3,
    english: 'candy',
    spanish: 'caramelo',
    example: 'Strawberry candies are my favorite.',
  },
  {
    id: 84,
    day: 4,
    english: 'captain',
    spanish: 'capitán/capitana',
    example: "The ship's captain looked worried.",
  },
  {
    id: 85,
    day: 5,
    english: 'car',
    spanish: 'coche/carro/auto',
    example: 'They need to fix their car.',
  },
  {
    id: 86,
    day: 6,
    english: 'card',
    spanish: 'tarjeta',
    example: 'Do you accept credit cards?',
  },
  {
    id: 87,
    day: 7,
    english: 'care',
    spanish: 'importar',
    example: "I don't care what you think.",
  },
  {
    id: 88,
    day: 8,
    english: 'case',
    spanish: 'caso',
    example: 'Call me in case you get lost.',
  },
  {
    id: 89,
    day: 9,
    english: 'cat',
    spanish: 'gato',
    example: 'The cat is eating right now.',
  },
  {
    id: 90,
    day: 10,
    english: 'catch',
    spanish: 'alcanzar algo o a alguien',
    example: 'We can catch the last train.',
  },
  {
    id: 91,
    day: 11,
    english: 'chair',
    spanish: 'silla',
    example: 'The books are on the chair.',
  },
  {
    id: 92,
    day: 12,
    english: 'chance',
    spanish: 'oportunidad',
    example: 'She had the chance to travel around the world.',
  },
  {
    id: 93,
    day: 13,
    english: 'change',
    spanish: 'cambiar',
    example: 'Prices can change anytime.',
  },
  {
    id: 94,
    day: 14,
    english: 'check',
    spanish: 'revisar',
    example: 'Students have to check their exams.',
  },
  {
    id: 95,
    day: 15,
    english: 'chicken',
    spanish: 'pollo',
    example: 'Do you like chicken with fries?',
  },
  {
    id: 96,
    day: 16,
    english: 'child',
    spanish: 'niño/niña',
    example: 'This child is adorable.',
  },
  {
    id: 97,
    day: 17,
    english: 'choice',
    spanish: 'elección',
    example: "It wasn't a good choice.",
  },
  {
    id: 98,
    day: 18,
    english: 'choose',
    spanish: 'elegir',
    example: 'You have many options to choose.',
  },
  {
    id: 99,
    day: 19,
    english: 'city',
    spanish: 'ciudad',
    example: 'This city is lovely.',
  },
  {
    id: 100,
    day: 20,
    english: 'class',
    spanish: 'clase',
    example: 'It was an interesting class.',
  },
  {
    id: 101,
    day: 1,
    english: 'clean',
    spanish: 'limpiar',
    example: 'We must clean the house every day.',
  },
  {
    id: 102,
    day: 2,
    english: 'clear',
    spanish: 'claro/clara',
    example: 'The instructions are clear.',
  },
  {
    id: 103,
    day: 3,
    english: 'close',
    spanish: 'cerca/cercano/cercana',
    example: 'The store is close.',
  },
  {
    id: 104,
    day: 4,
    english: 'close',
    spanish: 'cerrar',
    example: 'May I close the window?',
  },
  {
    id: 105,
    day: 5,
    english: 'clothes',
    spanish: 'ropa',
    example: 'I bought a lot of clothes.',
  },
  {
    id: 106,
    day: 6,
    english: 'club',
    spanish: 'club/asociación',
    example: 'The club has a great variety of amenities.',
  },
  {
    id: 107,
    day: 7,
    english: 'coffee',
    spanish: 'café',
    example: "She doesn't like to drink coffee.",
  },
  {
    id: 108,
    day: 8,
    english: 'cold',
    spanish: 'frío',
    example: 'It is getting cold.',
  },
  {
    id: 109,
    day: 9,
    english: 'college',
    spanish: 'facultad',
    example: 'They are college students.',
  },
  {
    id: 110,
    day: 10,
    english: 'come',
    spanish: 'venir',
    example: 'They will come to my house for Christmas.',
  },
  {
    id: 111,
    day: 11,
    english: 'company',
    spanish: 'compañía',
    example: 'He works for the power company.',
  },
  {
    id: 112,
    day: 12,
    english: 'completely',
    spanish: 'completamente',
    example: "I'm completely happy.",
  },
  {
    id: 113,
    day: 13,
    english: 'cookie',
    spanish: 'galleta',
    example: 'The girls like baking oat cookies.',
  },
  {
    id: 114,
    day: 14,
    english: 'cool',
    spanish: 'genial',
    example: 'She is a cool girl.',
  },
  {
    id: 115,
    day: 15,
    english: 'count',
    spanish: 'contar',
    example: 'The little boy learned to count until 10.',
  },
  {
    id: 116,
    day: 16,
    english: 'country',
    spanish: 'país',
    example: 'Canada is a big country.',
  },
  {
    id: 117,
    day: 17,
    english: 'couple',
    spanish: 'pareja',
    example: 'This resort is only for couples.',
  },
  {
    id: 118,
    day: 18,
    english: 'course',
    spanish: 'curso',
    example: 'I started the course three months ago.',
  },
  {
    id: 119,
    day: 19,
    english: 'cover',
    spanish: 'cubrir',
    example: "The insurance didn't cover the accident.",
  },
  {
    id: 120,
    day: 20,
    english: 'crazy',
    spanish: 'loco/loca',
    example: 'It is a crazy adventure.',
  },
  {
    id: 121,
    day: 1,
    english: 'cream',
    spanish: 'crema',
    example: 'Beat the cream until it takes consistency.',
  },
  {
    id: 122,
    day: 2,
    english: 'cry',
    spanish: 'llorar',
    example: 'Some little kids cry on the first day of school.',
  },
  {
    id: 123,
    day: 3,
    english: 'cut',
    spanish: 'cortar',
    example: 'I need a sharp knife to cute these carrots.',
  },
  {
    id: 124,
    day: 4,
    english: 'cute',
    spanish: 'lindo/linda',
    example: 'Her pet is so cute.',
  },
  {
    id: 125,
    day: 5,
    english: 'dad',
    spanish: 'papá',
    example: 'My dad is a mechanic.',
  },
  {
    id: 126,
    day: 6,
    english: 'dance',
    spanish: 'bailar',
    example: 'She can dance very well.',
  },
  {
    id: 127,
    day: 7,
    english: 'date',
    spanish: 'fecha',
    example: "There's no date on this letter.",
  },
  {
    id: 128,
    day: 8,
    english: 'date',
    spanish: 'salir con (alguien)',
    example: 'John used to date Sarah.',
  },
  {
    id: 129,
    day: 9,
    english: 'daughter',
    spanish: 'hija',
    example: "Amy's daughter is a great scientist.",
  },
  {
    id: 130,
    day: 10,
    english: 'day',
    spanish: 'día',
    example: 'It will be a sunny day.',
  },
  {
    id: 131,
    day: 11,
    english: 'dead',
    spanish: 'muerto/muerta',
    example: 'The Day of the Dead is a Mexican holiday.',
  },
  {
    id: 132,
    day: 12,
    english: 'deal',
    spanish: 'trato',
    example: "I made a deal with my sister that we wouldn't say anything.",
  },
  {
    id: 133,
    day: 13,
    english: 'dear',
    spanish: 'querido/querida',
    example: 'He was a dear friend.',
  },
  {
    id: 134,
    day: 14,
    english: 'death',
    spanish: 'muerte',
    example: 'War causes unnecessary death.',
  },
  {
    id: 135,
    day: 15,
    english: 'decide',
    spanish: 'decidir',
    example: 'She has to decide what to do.',
  },
  {
    id: 136,
    day: 16,
    english: 'definitely',
    spanish: 'definitivamente',
    example: "I'm definitely going to travel next year.",
  },
  {
    id: 137,
    day: 17,
    english: 'die',
    spanish: 'morir',
    example: 'He hopes to die peacefully.',
  },
  {
    id: 138,
    day: 18,
    english: 'different',
    spanish: 'diferente',
    example: 'They took different paths.',
  },
  {
    id: 139,
    day: 19,
    english: 'dinner',
    spanish: 'cena',
    example: 'We are having dinner.',
  },
  {
    id: 140,
    day: 20,
    english: 'do',
    spanish: 'hacer',
    example: 'They do their chores every day.',
  },
  {
    id: 141,
    day: 1,
    english: 'doctor',
    spanish: 'doctor/doctora',
    example: 'My cousin is a doctor.',
  },
  {
    id: 142,
    day: 2,
    english: 'dog',
    spanish: 'perro',
    example: 'The dog is eating some meat.',
  },
  {
    id: 143,
    day: 3,
    english: 'dollar',
    spanish: 'dólar',
    example: 'This cost 100 dollars.',
  },
  {
    id: 144,
    day: 4,
    english: 'door',
    spanish: 'puerta',
    example: 'The postman is at the door.',
  },
  {
    id: 145,
    day: 5,
    english: 'down',
    spanish: 'abajo',
    example: 'Can I ask you to put that down?',
  },
  {
    id: 146,
    day: 6,
    english: 'dream',
    spanish: 'sueño',
    example: 'I had a nice dream last night.',
  },
  {
    id: 147,
    day: 7,
    english: 'dress',
    spanish: 'vestirse',
    example: 'She quickly dressed her son.',
  },
  {
    id: 148,
    day: 8,
    english: 'drink',
    spanish: 'beber',
    example: 'Can I have something to drink?',
  },
  {
    id: 149,
    day: 9,
    english: 'drink',
    spanish: 'bebida',
    example: 'Thanks a lot for the drink.',
  },
  {
    id: 150,
    day: 10,
    english: 'drive',
    spanish: 'conducir',
    example: "I don't drive to work on Mondays.",
  },
  {
    id: 151,
    day: 11,
    english: 'drop',
    spanish: 'soltar',
    example: 'Be careful not to drop your ice cream cone!',
  },
  {
    id: 152,
    day: 12,
    english: 'drug',
    spanish: 'medicina',
    example: 'The doctor recommends certain drugs.',
  },
  {
    id: 153,
    day: 13,
    english: 'dude',
    spanish: 'amigo',
    example: 'Martin is a good dude.',
  },
  {
    id: 154,
    day: 14,
    english: 'early',
    spanish: 'temprano',
    example: 'I get up early on the weekend.',
  },
  {
    id: 155,
    day: 15,
    english: 'easy',
    spanish: 'fácil',
    example: 'This task is so easy.',
  },
  {
    id: 156,
    day: 16,
    english: 'eat',
    spanish: 'comer',
    example: 'They often eat vegetables.',
  },
  {
    id: 157,
    day: 17,
    english: 'egg',
    spanish: 'huevo',
    example: 'She bought some fresh eggs.',
  },
  {
    id: 158,
    day: 18,
    english: 'else',
    spanish: 'más',
    example: "We don't want anything else.",
  },
  {
    id: 159,
    day: 19,
    english: 'embarrass',
    spanish: 'avergonzar',
    example: "I didn't mean to embarrass you.",
  },
  {
    id: 160,
    day: 20,
    english: 'end',
    spanish: 'finalizar/terminar',
    example: 'The race is about to end.',
  },
  {
    id: 161,
    day: 1,
    english: 'end',
    spanish: 'final',
    example: "This can't be the end.",
  },
  {
    id: 162,
    day: 2,
    english: 'enjoy',
    spanish: 'disfrutar',
    example: 'She enjoys going out with friends.',
  },
  {
    id: 163,
    day: 3,
    english: 'entire',
    spanish: 'completo/completa',
    example: 'The entire class lasted 3 hours.',
  },
  {
    id: 164,
    day: 4,
    english: 'even',
    spanish: 'incluso',
    example: 'Her day got even worse.',
  },
  {
    id: 165,
    day: 5,
    english: 'evening',
    spanish: 'noche',
    example: 'That was a perfect evening.',
  },
  {
    id: 166,
    day: 6,
    english: 'ever',
    spanish: 'alguna vez',
    example: 'Have you ever traveled abroad?',
  },
  {
    id: 167,
    day: 7,
    english: 'exactly',
    spanish: 'exactamente',
    example: "It's exactly half past eight.",
  },
  {
    id: 168,
    day: 8,
    english: 'excite',
    spanish: 'emocionar',
    example: 'Planning my trip excites me.',
  },
  {
    id: 169,
    day: 9,
    english: 'excuse',
    spanish: 'justificar',
    example: 'The company will excuse his absence.',
  },
  {
    id: 170,
    day: 10,
    english: 'expect',
    spanish: 'esperar',
    example: 'I expect he has forgiven me.',
  },
  {
    id: 171,
    day: 11,
    english: 'explain',
    spanish: 'explicar',
    example: 'Can you explain a bit more?',
  },
  {
    id: 172,
    day: 12,
    english: 'eye',
    spanish: 'ojo',
    example: 'His eyes are green.',
  },
  {
    id: 173,
    day: 13,
    english: 'face',
    spanish: 'cara',
    example: 'You should wash your face in the morning.',
  },
  {
    id: 174,
    day: 14,
    english: 'face',
    spanish: 'enfrentar',
    example: "I can't face reality.",
  },
  {
    id: 175,
    day: 15,
    english: 'fact',
    spanish: 'hecho',
    example: 'Only few people know that fact.',
  },
  {
    id: 176,
    day: 16,
    english: 'fair',
    spanish: 'justo/justa',
    example: "I think her comment wasn't fair.",
  },
  {
    id: 177,
    day: 17,
    english: 'fall',
    spanish: 'caer',
    example: 'I might fall from the roof.',
  },
  {
    id: 178,
    day: 18,
    english: 'family',
    spanish: 'familia',
    example: "Jane's family is small.",
  },
  {
    id: 179,
    day: 19,
    english: 'far',
    spanish: 'lejos',
    example: 'The bank is not far from here.',
  },
  {
    id: 180,
    day: 20,
    english: 'fast',
    spanish: 'rápido/rápida',
    example: 'They can run very fast.',
  },
  {
    id: 181,
    day: 1,
    english: 'fat',
    spanish: 'gordo/gorda',
    example: 'My dog is getting a bit fat.',
  },
  {
    id: 182,
    day: 2,
    english: 'father',
    spanish: 'padre',
    example: 'Her father is a good businessman.',
  },
  {
    id: 183,
    day: 3,
    english: 'fault',
    spanish: 'culpa',
    example: 'Sorry, it was my fault.',
  },
  {
    id: 184,
    day: 4,
    english: 'favor',
    spanish: 'favor',
    example: 'Can I ask you a favor?',
  },
  {
    id: 185,
    day: 5,
    english: 'favorite',
    spanish: 'favorito/favorita',
    example: 'Hamburguers are my favorite food.',
  },
  {
    id: 186,
    day: 6,
    english: 'feel',
    spanish: 'sentir',
    example: 'She feels angry.',
  },
  {
    id: 187,
    day: 7,
    english: 'feeling',
    spanish: 'sentimiento',
    example: 'I have a feeling that I have seen him before.',
  },
  {
    id: 188,
    day: 8,
    english: 'fight',
    spanish: 'luchar',
    example: 'Soldiers are ready to fight.',
  },
  {
    id: 189,
    day: 9,
    english: 'fight',
    spanish: 'lucha',
    example: "Don't give up without a fight.",
  },
  {
    id: 190,
    day: 10,
    english: 'figure',
    spanish: 'imaginar',
    example: "I didn't figure you would get mad.",
  },
  { id: 191, day: null, english: 'fill', spanish: 'llenar', example: '' },
  {
    id: 192,
    day: null,
    english: 'finally',
    spanish: 'finalmente',
    example: '',
  },
  { id: 193, day: null, english: 'find', spanish: 'encontrar', example: '' },
  { id: 194, day: null, english: 'fine', spanish: 'bien', example: '' },
  { id: 195, day: null, english: 'finger', spanish: 'dedo', example: '' },
  { id: 196, day: null, english: 'finish', spanish: 'terminar', example: '' },
  { id: 197, day: null, english: 'fire', spanish: 'disparar', example: '' },
  { id: 198, day: null, english: 'fire', spanish: 'fuego', example: '' },
  { id: 199, day: null, english: 'fish', spanish: 'pez/pescado', example: '' },
  { id: 200, day: null, english: 'fix', spanish: 'arreglar', example: '' },
  { id: 201, day: null, english: 'floor', spanish: 'piso', example: '' },
  { id: 202, day: null, english: 'fly', spanish: 'volar', example: '' },
  { id: 203, day: null, english: 'follow', spanish: 'seguir', example: '' },
  { id: 204, day: null, english: 'food', spanish: 'comida', example: '' },
  { id: 205, day: null, english: 'foot', spanish: 'pie', example: '' },
  {
    id: 206,
    day: null,
    english: 'forever',
    spanish: 'por siempre',
    example: '',
  },
  { id: 207, day: null, english: 'forget', spanish: 'olvidar', example: '' },
  { id: 208, day: null, english: 'freak', spanish: 'enloquecer', example: '' },
  { id: 209, day: null, english: 'free', spanish: 'gratis', example: '' },
  {
    id: 210,
    day: null,
    english: 'friend',
    spanish: 'amigo/amiga',
    example: '',
  },
  { id: 211, day: null, english: 'front', spanish: 'frente', example: '' },
  { id: 212, day: null, english: 'full', spanish: 'lleno', example: '' },
  { id: 213, day: null, english: 'fun', spanish: 'diversión', example: '' },
  {
    id: 214,
    day: null,
    english: 'funny',
    spanish: 'graciosa/garcioso',
    example: '',
  },
  { id: 215, day: null, english: 'future', spanish: 'futuro', example: '' },
  { id: 216, day: null, english: 'game', spanish: 'juego', example: '' },
  {
    id: 217,
    day: null,
    english: 'gentleman',
    spanish: 'caballero',
    example: '',
  },
  {
    id: 218,
    day: null,
    english: 'get',
    spanish: 'conseguir/obtener',
    example: '',
  },
  { id: 219, day: null, english: 'gift', spanish: 'regalo', example: '' },
  { id: 220, day: null, english: 'girl', spanish: 'niña/chica', example: '' },
  { id: 221, day: null, english: 'girlfriend', spanish: 'novia', example: '' },
  { id: 222, day: null, english: 'give', spanish: 'dar', example: '' },
  {
    id: 223,
    day: null,
    english: 'glad',
    spanish: 'contenta/contento',
    example: '',
  },
  { id: 224, day: null, english: 'go', spanish: 'ir', example: '' },
  { id: 225, day: null, english: 'God', spanish: 'Dios', example: '' },
  { id: 226, day: null, english: 'good', spanish: 'buena/bueno', example: '' },
  {
    id: 227,
    day: null,
    english: 'grab',
    spanish: 'agarrar/coger',
    example: '',
  },
  { id: 228, day: null, english: 'great', spanish: 'genial', example: '' },
  { id: 229, day: null, english: 'group', spanish: 'grupo', example: '' },
  { id: 230, day: null, english: 'grow', spanish: 'crecer', example: '' },
  { id: 231, day: null, english: 'guess', spanish: 'adivinar', example: '' },
  { id: 232, day: null, english: 'gun', spanish: 'arma', example: '' },
  { id: 233, day: null, english: 'guy', spanish: 'tipo/chico', example: '' },
  { id: 234, day: null, english: 'hair', spanish: 'pelo/cabello', example: '' },
  { id: 235, day: null, english: 'hand', spanish: 'mano', example: '' },
  { id: 236, day: null, english: 'hand', spanish: 'dar (verb)', example: '' },
  { id: 237, day: null, english: 'handle', spanish: 'manejar', example: '' },
  { id: 238, day: null, english: 'hang', spanish: 'colgar', example: '' },
  { id: 239, day: null, english: 'happen', spanish: 'suceder', example: '' },
  { id: 240, day: null, english: 'happy', spanish: 'feliz', example: '' },
  { id: 241, day: null, english: 'hard', spanish: 'difícil', example: '' },
  { id: 242, day: null, english: 'hat', spanish: 'sombrero', example: '' },
  { id: 243, day: null, english: 'hate', spanish: 'odiar', example: '' },
  { id: 244, day: null, english: 'have', spanish: 'tener', example: '' },
  { id: 245, day: null, english: 'head', spanish: 'cabeza', example: '' },
  { id: 246, day: null, english: 'hear', spanish: 'escuchar', example: '' },
  { id: 247, day: null, english: 'heart', spanish: 'corazón', example: '' },
  { id: 248, day: null, english: 'hell', spanish: 'infierno', example: '' },
  {
    id: 249,
    day: null,
    english: 'help',
    spanish: 'ayudar (verb)',
    example: '',
  },
  { id: 250, day: null, english: 'help', spanish: 'ayuda', example: '' },
  { id: 251, day: null, english: 'here', spanish: 'aquí', example: '' },
  { id: 252, day: null, english: 'hide', spanish: 'esconder', example: '' },
  { id: 253, day: null, english: 'high', spanish: 'alto', example: '' },
  { id: 254, day: null, english: 'history', spanish: 'historia', example: '' },
  { id: 255, day: null, english: 'hit', spanish: 'golpear', example: '' },
  { id: 256, day: null, english: 'hold', spanish: 'tener', example: '' },
  { id: 257, day: null, english: 'home', spanish: 'casa/hogar', example: '' },
  { id: 258, day: null, english: 'honey', spanish: 'miel/cariño', example: '' },
  { id: 259, day: null, english: 'hope', spanish: 'esperar', example: '' },
  { id: 260, day: null, english: 'horrible', spanish: 'horrible', example: '' },
  { id: 261, day: null, english: 'hospital', spanish: 'hospital', example: '' },
  {
    id: 262,
    day: null,
    english: 'hot',
    spanish: 'caliente/caluroso',
    example: '',
  },
  { id: 263, day: null, english: 'hour', spanish: 'hora', example: '' },
  {
    id: 264,
    day: null,
    english: 'house',
    spanish: 'casa/vivienda',
    example: '',
  },
  { id: 265, day: null, english: 'how', spanish: 'como', example: '' },
  { id: 266, day: null, english: 'huge', spanish: 'enorme', example: '' },
  {
    id: 267,
    day: null,
    english: 'human',
    spanish: 'humana/humano',
    example: '',
  },
  { id: 268, day: null, english: 'hurt', spanish: 'lastimar', example: '' },
  {
    id: 269,
    day: null,
    english: 'husband',
    spanish: 'esposo/marido',
    example: '',
  },
  { id: 270, day: null, english: 'ice', spanish: 'hielo', example: '' },
  { id: 271, day: null, english: 'idea', spanish: 'idea', example: '' },
  { id: 272, day: null, english: 'imagine', spanish: 'imaginar', example: '' },
  {
    id: 273,
    day: null,
    english: 'important',
    spanish: 'importante',
    example: '',
  },
  { id: 274, day: null, english: 'instead', spanish: 'en cambio', example: '' },
  {
    id: 275,
    day: null,
    english: 'interesting',
    spanish: 'interesante',
    example: '',
  },
  { id: 276, day: null, english: 'invite', spanish: 'invitar', example: '' },
  { id: 277, day: null, english: 'job', spanish: 'trabajo', example: '' },
  { id: 278, day: null, english: 'join', spanish: 'unirse', example: '' },
  { id: 279, day: null, english: 'joke', spanish: 'broma', example: '' },
  { id: 280, day: null, english: 'jump', spanish: 'saltar', example: '' },
  { id: 281, day: null, english: 'just', spanish: 'solo', example: '' },
  {
    id: 282,
    day: null,
    english: 'keep',
    spanish: 'mantener/seguir',
    example: '',
  },
  { id: 283, day: null, english: 'key', spanish: 'llave/clave', example: '' },
  { id: 284, day: null, english: 'kick', spanish: 'patear', example: '' },
  { id: 285, day: null, english: 'kid', spanish: 'niña/niño', example: '' },
  {
    id: 286,
    day: null,
    english: 'kid',
    spanish: 'bromear (verb)',
    example: '',
  },
  { id: 287, day: null, english: 'kill', spanish: 'matar', example: '' },
  { id: 288, day: null, english: 'kind', spanish: 'tipo', example: '' },
  { id: 289, day: null, english: 'king', spanish: 'rey', example: '' },
  { id: 290, day: null, english: 'kiss', spanish: 'beso', example: '' },
  { id: 291, day: null, english: 'knock', spanish: 'golpear', example: '' },
  {
    id: 292,
    day: null,
    english: 'know',
    spanish: 'conocer/saber',
    example: '',
  },
  { id: 293, day: null, english: 'lady', spanish: 'señora', example: '' },
  { id: 294, day: null, english: 'last', spanish: 'durar', example: '' },
  { id: 295, day: null, english: 'late', spanish: 'tarde', example: '' },
  { id: 296, day: null, english: 'laugh', spanish: 'reir', example: '' },
  { id: 297, day: null, english: 'law', spanish: 'ley', example: '' },
  { id: 298, day: null, english: 'learn', spanish: 'aprender', example: '' },
  { id: 299, day: null, english: 'leave', spanish: 'dejar/salir', example: '' },
  { id: 300, day: null, english: 'leg', spanish: 'pierna/pata', example: '' },
  {
    id: 301,
    day: null,
    english: 'let',
    spanish: 'dejar/permitir',
    example: '',
  },
  { id: 302, day: null, english: 'lie', spanish: 'mentir', example: '' },
  { id: 303, day: null, english: 'life', spanish: 'vida', example: '' },
  { id: 304, day: null, english: 'light', spanish: 'luz', example: '' },
  {
    id: 305,
    day: null,
    english: 'like',
    spanish: 'gustar (verb)',
    example: '',
  },
  {
    id: 306,
    day: null,
    english: 'like',
    spanish: 'aproximadamente',
    example: '',
  },
  { id: 307, day: null, english: 'line', spanish: 'línea', example: '' },
  { id: 308, day: null, english: 'list', spanish: 'lista', example: '' },
  { id: 309, day: null, english: 'listen', spanish: 'escuchar', example: '' },
  {
    id: 310,
    day: null,
    english: 'little',
    spanish: 'pequeña/pequeño',
    example: '',
  },
  { id: 311, day: null, english: 'live', spanish: 'vivir', example: '' },
  { id: 312, day: null, english: 'long', spanish: 'mucho', example: '' },
  { id: 313, day: null, english: 'long', spanish: 'larga/largo', example: '' },
  { id: 314, day: null, english: 'look', spanish: 'mirar (verb)', example: '' },
  { id: 315, day: null, english: 'look', spanish: 'apariencia', example: '' },
  { id: 316, day: null, english: 'lord', spanish: 'señor', example: '' },
  { id: 317, day: null, english: 'lose', spanish: 'perder', example: '' },
  { id: 318, day: null, english: 'lot', spanish: 'mucha/mucho', example: '' },
  { id: 319, day: null, english: 'love', spanish: 'amar (verb)', example: '' },
  { id: 320, day: null, english: 'love', spanish: 'amor', example: '' },
  { id: 321, day: null, english: 'luck', spanish: 'suerte', example: '' },
  {
    id: 322,
    day: null,
    english: 'lucky',
    spanish: 'afortunada/afortunado',
    example: '',
  },
  { id: 323, day: null, english: 'lunch', spanish: 'almuerzo', example: '' },
  { id: 324, day: null, english: 'machine', spanish: 'máquina', example: '' },
  {
    id: 325,
    day: null,
    english: 'mad',
    spanish: 'enojada/enojado',
    example: '',
  },
  { id: 326, day: null, english: 'make', spanish: 'hacer', example: '' },
  { id: 327, day: null, english: 'man', spanish: 'hombre', example: '' },
  //{ id: , day: null, english: '', spanish: '', example: '' }
];

export const getNumberDays = () => {
  let numberDays = 0;
  for (const obj of WORDS) if (obj.day > numberDays) numberDays = obj.day;
  return numberDays;
};

export const getAllWords = () => {
  return WORDS.filter((word) => word.day);
};

export const getDayWords = (day) => {
  return WORDS.filter((word) => word.day === day);
};
